### ISSUE TITLE
Heroku Friendly?

### ISSUE THREAD

**Issue by zcrowe** [workflowproducts/envelope#30]
Hi Guys,

Firstly - wow!  Some of the best open source documentation I've ever come accross - great work :)

This is kind of a lazy question, but will envelope run on heroku?

**Comment by justintocci** [comment]
Thank you very much, we glad you like it! Please report any bugs! We turn them around as quick as we can.

So far we've been able to accommodate all users that make a suggestion. Now that you mention Heroku we'll put some resources into answering that question. Hopefully, this question won't be the end of a long unbroken run! However, I'd ask you to give us a couple weeks or so on this. 

I did some checking and I found that [Heroku can run C applications](https://elements.heroku.com/buildpacks/madouz/heroku-buildpack-c)

This seems to indicate that yes, in fact, we may be able to get Envelope running in Heroku. Since we don't need to put Envelope behind a web server this seems like something we can afford to do. We don't really know how much effort it will take. I figure we can afford to put ten hours into this since Heroku is a big thing in the PostgreSQL world. If it goes beyond ten we'll have to consider whether we can afford to move forward.

I'm assigning Joseph and Nunzio to look into this. We'll try not to make a new repo for Heroku specific code but we'll have to split it out the moment it becomes complex.

If you have any suggestions or expertise, know that we're interested.

Thank you again.

**Comment by zcrowe** [comment]
I think theonly issue with Heroku may be user auth - as I currently understand it, you can only have one database user?

Has anyone at your end tried it out?

If not let me know and I'll give it a whurl!

**Comment by justintocci** [comment]
Envelope should work fine with one user.  We haven't tried Heroku yet but only because we haven't gotten to it.

Regarding users, I saw this: [Heroku users](https://devcenter.heroku.com/articles/org-users-access) and yes, it would appear that you need an Enterprise account to use Roles in Heroku.

They don't post Enterprise pricing. I expect anyone who uses Heroku is going to want multiple users to be able to log in. This is really bad for Envelope on Heroku. Our whole security story revolves around the beauty of managing all that inside PostgreSQL. 

Zcrowe, I'm going to have to put this project on hold. We're a very small company and I don't see how putting our limited resources in this direction is going to help Envelope users. If I'm missing something please speak up and we'll discuss it further. We'll keep an open mind.

Meanwhile, Envelope runs very well on Linode, even the $10/mo tier is excellent. And I suspect that most users are doing local installs since PostgreSQL runs so well on old hardware with an SSD.

Nunzio, Joseph, give this an hour at most. If you can get it running then great. If not, let's discuss.

**Comment by justintocci** [comment]
There's been no further comment on this from the community so I'm going to close this.

The real deal breaker was that Heroku disables our whole security story. By making it so that developers can't host user permissions inside PostgreSQL, it places Envelope at a disadvantage. I'd rather not invest in it.
