### ISSUE TITLE
GS-date and GS-time send empty string when empty

### ISSUE THREAD

**Issue by crosstocci** [workflowproducts/envelope#34]
When update a GS-date by clearing it out it sends empty string instead of NULL.  When a GS-date is empty set the value accessor  to NULL.

**Comment by michaeltocci** [comment]
This issue is refering to the AJAX Update API.

I'm thinking that when someone tries to update a non-string type column to empty string, Envelope should translate that to NULL.

When emptying a gs-date field, this is what Envelope does right now:
```
 UPDATE yourview
    SET yourcolumn = ''::date
  WHERE yourwhere
```

I believe we should do something like this:
```
 UPDATE yourview
    SET yourcolumn = NULLIF('', '')::date
  WHERE yourwhere
```

The `NULLIF` will translate empty-string values (which _can't_ be cast to dates, integers, timestamps, etc) into `NULL` (which _can_ be cast to dates, integers, timestamps, etc).

**Comment by nunziotocci** [comment]
@michaeltocci, it is already in the http API to replace the string 'NULL' with and actual NULL value, so wherever you send empty string for dates, times, etc, you just need to send NULL.

This wouldn't change our current API at all.

**Comment by crosstocci** [comment]
Gs-date and gs-time now send 'NULL' instead of ''.
