### ISSUE TITLE
login_group is not in Envelope

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#6]
In previous version of Envelope, we restricted access to normal_g, we have a similar feature in Postage, where you can choose what group.

It would be nice to have this feature in Envelope.

**Comment by justintocci** [comment]
Here's what we're going to do:

1) make the config group setting the same for envelope as it is in postage now.
2) document it in the man page
3) Make it so that when a user logs in, if they don't have envelope_g, then it will say why they were rejected.
4) make sure that if the configure setting for group is set to envelope_g, and a superuser does NOT have envelope_g, then they cannot log in.
5) make the config file default to envelope_g for the login group setting.

**Comment by josephtocci** [comment]
Fixed, will be fixed in next release.
