### ISSUE TITLE
GS-Switch if statement templating issue

### ISSUE THREAD

**Issue by michaeltocci** [workflowproducts/envelope#63]
Doing an `X > Y` if statement in the template doesn't work because the `>` is encoded to `&gt;`.

**Comment by nunziotocci** [comment]
Unfortunately we can't do anything about the encoding, because the browser is doing it before we ever get the template.
Here is my plan:
1. Write and document `gt(x,y)`, `gte(x,y)`, `lt(x,y)` and `lte(x,y)` functions for use with templates.
2. Add warnings to all templated elements if it detects `&gt;` or `&lt;`

**Comment by josephtocci** [comment]
Why not just convert it back? Shouldn't it just work at that point?

**Comment by nunziotocci** [comment]
@josephtocci Converting it back would be very complicated and would involve modifying doT.js and it's easier to just do the functions and the warnings.

**Comment by nunziotocci** [comment]
Fixed.
Will be seen in next release.
