### ISSUE TITLE
List box needs to be able to select multiple records

### ISSUE THREAD

**Issue by justintocci** [workflowproducts/envelope#69]
List box needs to be able to select multiple records.

Typical use case is to choose several items, then get an array and do something with it. Not typically bound to a column in this case but should work bound or unbound.

**Comment by josephtocci** [comment]
The paradigm we have decided on is click to select a single record, shift click to select a range starting with the previously selected record, and shift/control click to toggle, both in and outside the range. But shift clicking simply adjusts the previous range, it doesn't add another one. This is a commonly accepted paradigm for multi-select of a list and I can't think of anything better.

Mobile:
Since there is no shift/command/control/option on mobile devices, I think we're just going to do click to toggle. I don't think there is any other way to handle it.

**Comment by justintocci** [comment]
yes, you've got it.

**Comment by crosstocci** [comment]
On desktop control-click will add a new select origin, which can be adjusted with shift-click separately from the other origin points.

**Comment by crosstocci** [comment]
Fixed in next release.
