### ISSUE TITLE
Use miniz for Envelope ZIP Actions

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#7]
In previous versions of the Envelope File Manager, we hade zip/unzip functionality.

@michaeltocci, we should get together and figure out a good request format so we can re-impliment this functionality using miniz.

**Comment by nunziotocci** [comment]
@michaeltocci, How does this look?

```
FILE<tab>ZIP<tab><folder path><tab><zip destination><newline>
FILE<tab>UNZIP<tab><zip path><tab><destination folder><newline>
```

**Comment by michaeltocci** [comment]
That looks good, it's flexible and simple. I took a brief skim of the man pages for `zip` and `unzip`, there are parameters that we may want to have the option of sending at some point. Can you write the code to be upwind of sending parameters?

**Comment by justintocci** [comment]
Yeah, the only problem is it won't work in the file manager interface.

Currently, the file manager allows you to check off multiple items in multiple locations, then do an operation on them. This wouldn't allow you to send multiple items that weren't in the same folder. I think you should just not do it rather than break the existing file manager convention.
