### ISSUE TITLE
PostgreSQL bytea accept_ function not being decoded

### ISSUE THREAD

**Issue by nunziotocci** [workflowproducts/envelope#73]
I have a .wav file stored in the database and would like to be able to download it with an accept_ function.

**Comment by justintocci** [comment]
My thinking is that we don't need this. I am open-minded if the community speaks up but here is what I am thinking.

Storing .wav files in the database is not something that people should do generally, and in those rare cases where it seems ok, I would express caution. It should not be done without careful consideration. 

But let's say they really need to do it. We aren't going to be able to solve their problems without re-architecting Envelope or at the very least, building an additional API just for this. In fact, an API most likely wouldn't work, we'd probably need to build a companion program. Because for this kind of data you must stream, there isn't really any other way to do it right. 

For these reasons, and until I hear of a use case that causes me to re-think it, it wouldn't be smart for us to spend that much in resources on such a niche feature.

However, there is little lost. Most users, if not all of them, will find they can do many different things within Envelope that will work very well. People should start with #1 on this list and work their way down until they find the best fit for their use case.
1) Use Envelope for access control and store/fetch the files from the file system(the 'role' folder was made for this use case). 
2) fetch a text representation of the data through Envelope and make it a binary in the javascript. 
3) provide a way around Envelope.
