### ISSUE TITLE
Sqlite support

### ISSUE THREAD

**Issue by Immortalin** [workflowproducts/envelope#81]
Can sqlite support be added? This would allow for self contained apps without having to setup and configure a DB

**Comment by justintocci** [comment]
We have no experience with SQLite, however, if you're looking for a self-contained app, have you looked at Electron? If you're considering Electron you should check out our repos [here](https://github.com/workflowproducts).

We have postcard, which embeds PostgreSQL into Electron apps and Letterbox which embeds Envelope into Electron apps. There are also example projects you can use to start your own!

**Comment by justintocci** [comment]
@immortalin 

If you'd really prefer embedded Sqlite as opposed to embedded PostgreSQL as described above then there are some things you should know.

Previously, we had a client that wanted Envelope to work with MS SQL Server. We wrote that no problem and it worked great. We used ODBC so with very little work we could support most databases with an ODBC driver (in order to support a database there needs to be a way to set the session user. I'm not sure SQLite has that.)

Unfortunately, the ODBC version of Envelope failed to get traction beyond the one client. Every client since has preferred PostgreSQL so we haven't done any work on Envelope ODBC in a while.

The team doesn't want to release Envelope ODBC. because it would mean yet another issue tracker open to the public. We already have limited resources and we're unlikely to see a return on the investment. 

Consequently, the free version of Envelope currently supports PostgreSQL only and the ODBC version won't be released until we figure out a business model for it. 

Thank you for your interest. I hope you understand our situation. Feel free to call if you'd like to discuss the matter in a private forum.

**Comment by Immortalin** [comment]
@justintocci thanks
